### ISSUE TITLE
Simplify how videos are specified

### ISSUE THREAD

**Issue by san650** [fedwiki/wiki-plugin-video#14]
It would be a lot simpler for user to just copy and paste the full URL video on the text editor.

i.e.

```
http://youtu.be/ziMLDgsefi0
We show how to drag and drop pages into one browser tab before making them part of one wiki.
```

We could get the video key from the URL so the user don't have to.

**Comment by san650** [comment]
@WardCunningham Do you think this is worth implementing?

**Comment by WardCunningham** [comment]
The drop logic has url decoding. I wouldn't want to see that logic duplicated. There should be some way that the video plugin could handle the video url decoding and the drop logic delegate to it. I imagine some sort of bidding process among available plugins but I haven't worked out how that would be implemented. Its hard for the core javascrip to know what plugins are available until they are loaded.

The original goal was to support youtube and vimeo. It's grown since then and there is more regularity than I would have expected. Are you thinking some universal construction could handle all cases? 

The plugin goes to some effort to make sure there is a caption besides the video. This creates some place we can get user clicks for editing and dragging. I wouldn't want to break that.

**Comment by WardCunningham** [comment]
A crazy dream has been to have some community managed generalized page import mechanism that would read and understand pages from popular database-backed websites. For example, I read a lot of BBC news stories and would like to quote them with little effort. Here is a fantasy description of how that might work.
http://forage.ward.fed.wiki.org/bbc-world-service.html

Whenever I get frustrated with the video plugin I start thinking along these lines. Then I remind myself that I've promised much simpler things to others and turn my attention there.
